---
- name: Add static IPs for each preferred WiFi network to /etc/dhcpcd.conf
  become: yes
  become_user: root
  blockinfile:
    path: "/etc/dhcpcd.conf"
    block: |
      ssid null
      static ip_address=192.168.43.10{{ hostvars[inventory_hostname]['ansible_hostname'][-1] }}/24
      static routers=192.168.43.1
      static domain_name_servers=192.168.43.1

      ssid Schnauzer
      static ip_address=10.0.0.10{{ hostvars[inventory_hostname]['ansible_hostname'][-1] }}/24
      static routers=10.0.0.1
      static domain_name_servers=10.0.0.1

      ssid devers
      static ip_address=172.16.2.10{{ hostvars[inventory_hostname]['ansible_hostname'][-1] }}/24
      static routers=172.16.2.1
      static domain_name_servers=172.16.2.1
  tags: dhcpcd_update
