---
- block:
  - name: Reboot
    command: shutdown -r +0 'Ansible-triggered reboot'
    async: 0
    poll: 0
    ignore_errors: yes
    become: yes

  - name: Wait for reboot to finish
    local_action: wait_for host={{ inventory_hostname }} state=started port=22 delay=100 timeout=240
    become: no
  tags: reboot
